import { ToolDefinition } from '../types/ninja';

export const TOOLS: ToolDefinition[] = [
  // --- FILE TOOLS ---
  {
    id: 'pdf-compressor',
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    shortDescription: 'Reduce PDF file size without losing essential fidelity.',
    detailedDescription: 'Optimize and compress PDF documents by cleaning streams, unneeded metadata, and compressing internal document structures directly in your browser or server.',
    category: 'file',
    acceptedInputs: ['file'],
    fileTypes: ['.pdf', 'application/pdf'],
    icon: 'FileArchive',
    isPopular: true,
    isRecommended: true,
    seoTitle: 'Free Online PDF Compressor — NINJA Web Command Center',
    seoDescription: 'Compress your PDF documents quickly and securely without uploading to untrusted third parties.',
    keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'pdf optimizer'],
    faqs: [
      { question: 'Does compressing a PDF reduce text clarity?', answer: 'No, text streams remain vector sharp while redundant resources and metadata are stripped.' },
      { question: 'Is my PDF private?', answer: 'Yes, files are processed in a private secure session.' },
    ],
  },
  {
    id: 'pdf-merger',
    slug: 'pdf-merger',
    name: 'PDF Merger',
    shortDescription: 'Combine multiple PDF files into one clean document.',
    detailedDescription: 'Merge two or more PDF files into a single unified PDF with custom page ordering.',
    category: 'file',
    acceptedInputs: ['file'],
    fileTypes: ['.pdf', 'application/pdf'],
    icon: 'Layers',
    isPopular: true,
    seoTitle: 'Merge PDF Files Online — NINJA',
    seoDescription: 'Combine multiple PDF documents into one seamlessly in seconds.',
    keywords: ['merge pdf', 'combine pdf', 'join pdf'],
  },
  {
    id: 'pdf-splitter',
    slug: 'pdf-splitter',
    name: 'PDF Splitter',
    shortDescription: 'Extract specific pages or page ranges from any PDF.',
    detailedDescription: 'Separate pages from large PDF files into distinct, clean PDF documents.',
    category: 'file',
    acceptedInputs: ['file'],
    fileTypes: ['.pdf', 'application/pdf'],
    icon: 'Scissors',
    seoTitle: 'Split PDF Pages Online — NINJA',
    seoDescription: 'Extract specific pages or split PDF documents instantly.',
    keywords: ['split pdf', 'extract pdf pages', 'separate pdf'],
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDescription: 'Resize images to custom width, height, or social presets (1080x1080, 1920x1080).',
    detailedDescription: 'Set exact dimensions with aspect-ratio locking or pick standard presets for Instagram, Twitter/X, and YouTube.',
    category: 'file',
    acceptedInputs: ['file'],
    fileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    icon: 'Maximize2',
    isPopular: true,
    seoTitle: 'Image Resizer Online — 1080x1080, 4K & Custom Presets',
    seoDescription: 'Resize photos to exact dimensions or social media standards without losing quality.',
    keywords: ['resize image', '1080x1080', 'photo resizer', 'crop dimensions'],
  },
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Image Converter',
    shortDescription: 'Convert images seamlessly between JPG, PNG, and WEBP formats.',
    detailedDescription: 'Fast format conversion preserving transparency (PNG/WEBP) or optimizing size (JPG) with adjustable output quality.',
    category: 'file',
    acceptedInputs: ['file'],
    fileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    icon: 'RefreshCw',
    isPopular: true,
    seoTitle: 'Convert Image to JPG, PNG, WEBP — NINJA',
    seoDescription: 'Instant browser-side and server-side image format converter.',
    keywords: ['convert image to jpg', 'png to jpg', 'webp to png'],
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Shrink photo file sizes with custom compression factor.',
    detailedDescription: 'Reduce MBs down to KBs for faster web uploads and email attachments.',
    category: 'file',
    acceptedInputs: ['file'],
    fileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    icon: 'Minimize2',
    isPopular: true,
    seoTitle: 'Online Image Compressor — NINJA',
    seoDescription: 'Compress JPG, PNG, and WEBP photos with smart compression.',
    keywords: ['compress image', 'reduce photo size', 'shrink photo'],
  },
  {
    id: 'file-metadata',
    slug: 'file-metadata',
    name: 'File Inspector & Metadata',
    shortDescription: 'Inspect exact file byte size, MIME type, dimensions, and checksums.',
    detailedDescription: 'Examine detailed technical headers and properties of uploaded documents or media files.',
    category: 'file',
    acceptedInputs: ['file'],
    icon: 'FileSearch',
    seoTitle: 'File Metadata Inspector — NINJA',
    seoDescription: 'View deep technical metadata of any file safely.',
    keywords: ['file metadata', 'file info', 'mime inspector'],
  },

  // --- GENERATORS ---
  {
    id: 'qr-generator',
    slug: 'qr-generator',
    name: 'QR Code Generator',
    shortDescription: 'Generate crisp, downloadable high-res SVG or PNG QR codes.',
    detailedDescription: 'Create QR codes for website URLs, social profiles (Instagram, Twitter), WiFi credentials, or contact info.',
    category: 'generators',
    acceptedInputs: ['text'],
    icon: 'QrCode',
    isPopular: true,
    isRecommended: true,
    seoTitle: 'Free QR Code Generator — Custom Colors & SVG Download',
    seoDescription: 'Generate custom QR codes instantly for any link or text. Free, fast, vector ready.',
    keywords: ['qr code generator', 'create qr code', 'free qr maker'],
    faqs: [
      { question: 'Do these QR codes expire?', answer: 'No! These are standard static QR codes that will work forever.' },
      { question: 'Can I download as SVG and PNG?', answer: 'Yes, NINJA provides instant downloads in both raster and vector formats.' },
    ],
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Password Generator',
    shortDescription: 'Generate cryptographically strong passwords with custom length and rules.',
    detailedDescription: 'Create unbreakable passwords with alphanumeric, symbol, uppercase, and avoid-ambiguous-character toggles.',
    category: 'generators',
    acceptedInputs: ['none'],
    icon: 'KeyRound',
    isPopular: true,
    seoTitle: 'Cryptographically Secure Password Generator — NINJA',
    seoDescription: 'Generate random passwords using CSPRNG entropy with customizable length and character sets.',
    keywords: ['password generator', 'strong password', 'random password'],
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    shortDescription: 'Generate RFC4122 compliant UUID v4 identifiers in bulk.',
    detailedDescription: 'Generate single or batch UUIDs with uppercase/lowercase and hyphen options.',
    category: 'generators',
    acceptedInputs: ['none'],
    icon: 'Hash',
    seoTitle: 'Online UUID v4 Generator — NINJA',
    seoDescription: 'Generate random UUID v4 identifiers with one click.',
    keywords: ['uuid generator', 'guid generator', 'uuid v4'],
  },
  {
    id: 'lorem-generator',
    slug: 'lorem-generator',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Generate placeholder dummy text by words, sentences, or paragraphs.',
    detailedDescription: 'Generate clean mock content for design mockups, wireframes, and documentation.',
    category: 'generators',
    acceptedInputs: ['none'],
    icon: 'AlignLeft',
    seoTitle: 'Lorem Ipsum Dummy Text Generator — NINJA',
    seoDescription: 'Generate clean placeholder typography for mockups and tests.',
    keywords: ['lorem ipsum generator', 'dummy text', 'placeholder text'],
  },
  {
    id: 'color-palette',
    slug: 'color-palette',
    name: 'Color Palette Generator',
    shortDescription: 'Generate harmonious color palettes with hex, RGB, and contrast checks.',
    detailedDescription: 'Explore trending monochrome, complimentary, and triadic palettes ready to copy.',
    category: 'generators',
    acceptedInputs: ['none'],
    icon: 'Palette',
    seoTitle: 'Modern Color Palette Generator — NINJA',
    seoDescription: 'Generate beautiful hex and RGB color harmonies for web and graphic designers.',
    keywords: ['color palette generator', 'hex colors', 'color scheme'],
  },

  // --- CALCULATORS ---
  {
    id: 'emi-calculator',
    slug: 'emi-calculator',
    name: 'Loan & EMI Calculator',
    shortDescription: 'Calculate monthly EMI, total interest, and complete repayment breakdown.',
    detailedDescription: 'Plan home, car, or personal loans with accurate amortization formulas and total payable visualization.',
    category: 'calculators',
    acceptedInputs: ['number'],
    icon: 'Landmark',
    isPopular: true,
    isRecommended: true,
    seoTitle: 'Loan EMI Calculator with Interest Breakdown — NINJA',
    seoDescription: 'Calculate your monthly loan EMI with principal, rate, and tenure inputs.',
    keywords: ['emi calculator', 'loan calculator', 'calculate emi', 'car loan emi'],
    faqs: [
      { question: 'What is the formula used for EMI?', answer: 'EMI = [P x R x (1+R)^N] / [(1+R)^N - 1], where P is Principal, R is monthly rate, and N is months.' },
    ],
  },
  {
    id: 'basic-calculator',
    slug: 'basic-calculator',
    name: 'Quick Math & Expression Calculator',
    shortDescription: 'Evaluate mathematical expressions, powers, percentages, and roots.',
    detailedDescription: 'Type complex mathematical strings like "(45 * 12) + sqrt(144)" and compute instantly.',
    category: 'calculators',
    acceptedInputs: ['text'],
    icon: 'Calculator',
    seoTitle: 'Online Expression & Math Calculator — NINJA',
    seoDescription: 'Evaluate math equations and expressions with high precision.',
    keywords: ['math calculator', 'calculate online', 'expression calculator'],
  },
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription: 'Compute percentage increases, discounts, fractions, and proportions.',
    detailedDescription: 'Solve "What is X% of Y?", "X is what % of Y?", and percentage delta.',
    category: 'calculators',
    acceptedInputs: ['number'],
    icon: 'Percent',
    seoTitle: 'Percentage Calculator — Quick Math — NINJA',
    seoDescription: 'Calculate percentage discounts, increases, and fractions effortlessly.',
    keywords: ['percentage calculator', 'calculate percent', 'discount calculator'],
  },
  {
    id: 'gst-calculator',
    slug: 'gst-calculator',
    name: 'GST & Sales Tax Calculator',
    shortDescription: 'Calculate inclusive and exclusive GST rates with CGST / SGST split.',
    detailedDescription: 'Compute standard slabs (5%, 12%, 18%, 28%) or custom tax percentages with net and gross totals.',
    category: 'calculators',
    acceptedInputs: ['number'],
    icon: 'Receipt',
    seoTitle: 'GST Tax Calculator — Net & Gross Breakdown — NINJA',
    seoDescription: 'Calculate Goods and Services Tax inclusive and exclusive amounts.',
    keywords: ['gst calculator', 'sales tax calculator', 'tax breakdown'],
  },
  {
    id: 'age-calculator',
    slug: 'age-calculator',
    name: 'Age & Date Difference Calculator',
    shortDescription: 'Calculate exact age in years, months, days, hours, and days until next birthday.',
    detailedDescription: 'Compute exact time differences between any two dates or from birthdate to today.',
    category: 'calculators',
    acceptedInputs: ['text'],
    icon: 'Calendar',
    seoTitle: 'Age & Date Difference Calculator — NINJA',
    seoDescription: 'Calculate exact elapsed time between dates in years, months, and days.',
    keywords: ['age calculator', 'date difference', 'days between dates'],
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    name: 'Unit & Currency Converter',
    shortDescription: 'Convert currency (USD, INR, EUR, GBP), length, weight, speed, and temperature.',
    detailedDescription: 'Convert values between imperial and metric systems as well as global currency rates.',
    category: 'calculators',
    acceptedInputs: ['text'],
    icon: 'ArrowLeftRight',
    isPopular: true,
    seoTitle: 'Unit and Currency Converter — NINJA',
    seoDescription: 'Convert currency pairs and measurement units with live formulas.',
    keywords: ['currency converter', 'unit converter', 'usd to inr', 'kg to lbs'],
  },

  // --- TEXT TOOLS ---
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word & Character Counter',
    shortDescription: 'Real-time word, character, sentence, reading time, and speaking time analyzer.',
    detailedDescription: 'Deep text analytics including paragraph counts, lexical density, and reading speeds.',
    category: 'text',
    acceptedInputs: ['text'],
    icon: 'FileText',
    isPopular: true,
    seoTitle: 'Word and Character Counter — Reading Time — NINJA',
    seoDescription: 'Analyze word count, character count without spaces, and estimated reading time.',
    keywords: ['word counter', 'character count', 'reading time calculator'],
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Text Case Converter',
    shortDescription: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, and kebab-case.',
    detailedDescription: 'Standardize text formatting for programming identifiers, copy headlines, or clean transcripts.',
    category: 'text',
    acceptedInputs: ['text'],
    icon: 'Type',
    seoTitle: 'Case Converter — Title Case, camelCase, UPPERCASE — NINJA',
    seoDescription: 'Transform strings into any programming or writing case format in real time.',
    keywords: ['case converter', 'title case', 'camelcase converter', 'uppercase'],
  },
  {
    id: 'text-cleaner',
    slug: 'text-cleaner',
    name: 'Text Cleaner & Deduplicator',
    shortDescription: 'Strip duplicate lines, excess whitespace, empty lines, and HTML tags.',
    detailedDescription: 'Sanitize messy pasted text, sort lines alphabetically, and clean trailing spaces.',
    category: 'text',
    acceptedInputs: ['text'],
    icon: 'Sparkles',
    seoTitle: 'Text Cleaner & Duplicate Line Remover — NINJA',
    seoDescription: 'Remove duplicate lines, extra spaces, and tidy up raw strings effortlessly.',
    keywords: ['text cleaner', 'remove duplicate lines', 'whitespace remover'],
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDescription: 'Beautify, minify, and validate JSON payloads with syntax error detection.',
    detailedDescription: 'Format raw JSON with 2-space or 4-space indentation, validate syntax, and copy cleaned output.',
    category: 'text',
    acceptedInputs: ['text'],
    icon: 'Code',
    isPopular: true,
    isRecommended: true,
    seoTitle: 'JSON Formatter & Validator Online — NINJA',
    seoDescription: 'Format and validate JSON with line-by-line syntax error diagnostics.',
    keywords: ['json formatter', 'validate json', 'beautify json', 'json lint'],
  },

  // --- DEVELOPER TOOLS ---
  {
    id: 'base64-tool',
    slug: 'base64-tool',
    name: 'Base64 Encoder / Decoder',
    shortDescription: 'Encode and decode UTF-8 text and binary data to Base64 safely.',
    detailedDescription: 'Handles Unicode characters, padding adjustments, and URL-safe Base64 conversions.',
    category: 'developer',
    acceptedInputs: ['text'],
    icon: 'Binary',
    seoTitle: 'Base64 Encode & Decode Online — NINJA',
    seoDescription: 'Encode or decode strings to Base64 with UTF-8 support.',
    keywords: ['base64 encode', 'base64 decode', 'base64 tool'],
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    name: 'URL Encoder / Decoder',
    shortDescription: 'Encode query parameters and decode percent-encoded URLs.',
    detailedDescription: 'Convert special symbols to URI components and resolve percent-encoded strings.',
    category: 'developer',
    acceptedInputs: ['text'],
    icon: 'Link',
    seoTitle: 'URL Percent Encoder & Decoder — NINJA',
    seoDescription: 'Sanitize query strings and decode encoded URLs accurately.',
    keywords: ['url encode', 'url decode', 'percent encoding'],
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    name: 'JWT Debugger & Decoder',
    shortDescription: 'Decode JSON Web Token headers, payload claims, and expiration timestamps.',
    detailedDescription: 'Inspect token claims (iss, sub, exp, iat) securely on client-side without sending tokens to any server.',
    category: 'developer',
    acceptedInputs: ['text'],
    icon: 'ShieldCheck',
    isPopular: true,
    seoTitle: 'Client-Side JWT Decoder & Inspector — NINJA',
    seoDescription: 'Decode JWT tokens locally without exposing sensitive secrets to external servers.',
    keywords: ['jwt decoder', 'decode jwt', 'jwt debugger'],
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    name: 'Regex Tester & Matcher',
    shortDescription: 'Test regular expressions with flags (g, i, m, s) and highlight match groups.',
    detailedDescription: 'Interactive testing playground with match count, captured groups, and cheat sheet presets.',
    category: 'developer',
    acceptedInputs: ['text'],
    icon: 'SearchCode',
    seoTitle: 'Interactive Regex Tester — NINJA',
    seoDescription: 'Test regular expressions with instant group highlighting and flag controls.',
    keywords: ['regex tester', 'regular expression tester', 'regex match'],
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    name: 'UNIX Timestamp Converter',
    shortDescription: 'Convert epoch seconds or milliseconds to ISO, UTC, and local time strings.',
    detailedDescription: 'Inspect timestamps, see relative time ("3 hours ago"), and convert current time to Unix epoch.',
    category: 'developer',
    acceptedInputs: ['text'],
    icon: 'Clock',
    seoTitle: 'UNIX Timestamp Epoch Converter — NINJA',
    seoDescription: 'Convert Unix epoch time to human readable UTC and local dates.',
    keywords: ['unix timestamp', 'epoch converter', 'timestamp to date'],
  },

  // --- AI TOOLS (Backed by Gemini 3.8 Flash via backend) ---
  {
    id: 'text-summarizer',
    slug: 'text-summarizer',
    name: 'AI Document & Text Summarizer',
    shortDescription: 'Extract core takeaways, bullet summaries, and executive briefs from text or PDFs.',
    detailedDescription: 'Powered by Gemini AI. Condense long essays, meeting notes, research papers, and documents with high precision.',
    category: 'ai',
    acceptedInputs: ['text', 'file'],
    fileTypes: ['.pdf', '.txt'],
    icon: 'Sparkle',
    isPopular: true,
    isRecommended: true,
    seoTitle: 'AI Text and PDF Summarizer — NINJA',
    seoDescription: 'Condense documents, PDFs, and articles into bullet-point summaries using AI.',
    keywords: ['summarize pdf', 'ai summarizer', 'text summary', 'document condenser'],
  },
  {
    id: 'text-rewriter',
    slug: 'text-rewriter',
    name: 'AI Tone & Content Rewriter',
    shortDescription: 'Rewrite drafts to sound Professional, Casual, Persuasive, or Technical.',
    detailedDescription: 'Refine grammar, enhance vocabulary, and change stylistic tone for executive communication or copywriting.',
    category: 'ai',
    acceptedInputs: ['text'],
    icon: 'Wand2',
    isPopular: true,
    seoTitle: 'AI Text Rewriter & Tone Enhancer — NINJA',
    seoDescription: 'Improve your writing, polish grammar, and adjust tone with Gemini AI.',
    keywords: ['ai rewriter', 'tone changer', 'polish writing', 'rephrase text'],
  },
  {
    id: 'translator',
    slug: 'translator',
    name: 'AI Polyglot Translator',
    shortDescription: 'Translate text accurately preserving nuances into Kannada, Spanish, Hindi, German, Japanese, etc.',
    detailedDescription: 'Natural contextual translation powered by multilingual Gemini intelligence.',
    category: 'ai',
    acceptedInputs: ['text'],
    icon: 'Languages',
    isPopular: true,
    seoTitle: 'AI Language Translator — Kannada, Spanish, Hindi & More — NINJA',
    seoDescription: 'Contextual, natural language translation preserving meaning and nuance.',
    keywords: ['translate to kannada', 'language translator', 'ai translation'],
  },
  {
    id: 'resume-generator',
    slug: 'resume-generator',
    name: 'AI Resume & Bio Architect',
    shortDescription: 'Generate an ATS-optimized professional resume structure and impactful bullet points.',
    detailedDescription: 'Turn raw experience, skills, and target job titles into a modern high-impact resume ready to copy or download.',
    category: 'ai',
    acceptedInputs: ['text'],
    icon: 'Briefcase',
    isPopular: true,
    isRecommended: true,
    seoTitle: 'AI Resume Builder & Content Generator — NINJA',
    seoDescription: 'Build high-impact, ATS-friendly resumes and career summaries with Gemini AI.',
    keywords: ['generate resume', 'resume builder', 'ai cv maker'],
  },
  {
    id: 'email-generator',
    slug: 'email-generator',
    name: 'AI Professional Email Drafter',
    shortDescription: 'Draft formal cold emails, meeting follow-ups, and urgent executive requests in seconds.',
    detailedDescription: 'Generates subject line, salutation, clear body value proposition, and crisp call to action.',
    category: 'ai',
    acceptedInputs: ['text'],
    icon: 'Mail',
    seoTitle: 'AI Email Writer & Response Generator — NINJA',
    seoDescription: 'Generate clear, professional emails with compelling subject lines and tones.',
    keywords: ['email generator', 'ai email writer', 'draft business email'],
  },

  // --- WEB ACTIONS (Launcher) ---
  {
    id: 'open-whatsapp',
    slug: 'open-whatsapp',
    name: 'Open WhatsApp Web',
    shortDescription: 'Launch official WhatsApp Web messenger.',
    detailedDescription: 'Quickly open WhatsApp Web in a new tab or app window to message friends and team members.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'MessageSquare',
    isPopular: true,
    webUrl: 'https://web.whatsapp.com',
    seoTitle: 'Quick WhatsApp Web Launcher — NINJA',
    seoDescription: 'Launch WhatsApp Web instantly via command.',
    keywords: ['open whatsapp', 'whatsapp web', 'launch whatsapp'],
  },
  {
    id: 'open-instagram',
    slug: 'open-instagram',
    name: 'Open Instagram',
    shortDescription: 'Launch official Instagram web feed and messages.',
    detailedDescription: 'Navigate directly to Instagram in a clean web browser window.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'Camera',
    webUrl: 'https://www.instagram.com',
    seoTitle: 'Open Instagram — NINJA Web Launcher',
    seoDescription: 'Instant launcher for Instagram.',
    keywords: ['open instagram', 'instagram web'],
  },
  {
    id: 'open-youtube',
    slug: 'open-youtube',
    name: 'Open YouTube',
    shortDescription: 'Launch YouTube video streaming platform.',
    detailedDescription: 'Open YouTube to search videos, tutorials, or music.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'PlaySquare',
    webUrl: 'https://www.youtube.com',
    seoTitle: 'Open YouTube — NINJA Web Launcher',
    seoDescription: 'Instant launcher for YouTube.',
    keywords: ['open youtube', 'youtube web'],
  },
  {
    id: 'open-linkedin',
    slug: 'open-linkedin',
    name: 'Open LinkedIn',
    shortDescription: 'Launch professional networking feed on LinkedIn.',
    detailedDescription: 'Open LinkedIn to check notifications, network connections, and career updates.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'Share2',
    webUrl: 'https://www.linkedin.com',
    seoTitle: 'Open LinkedIn — NINJA Web Launcher',
    seoDescription: 'Instant launcher for LinkedIn.',
    keywords: ['open linkedin', 'linkedin web'],
  },
  {
    id: 'open-github',
    slug: 'open-github',
    name: 'Open GitHub',
    shortDescription: 'Launch GitHub repository hub and pull requests.',
    detailedDescription: 'Navigate straight to GitHub developer platform.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'GitPullRequest',
    webUrl: 'https://github.com',
    seoTitle: 'Open GitHub — NINJA Web Launcher',
    seoDescription: 'Instant launcher for GitHub.',
    keywords: ['open github', 'github web'],
  },
  {
    id: 'open-gmail',
    slug: 'open-gmail',
    name: 'Open Gmail',
    shortDescription: 'Launch Google Mail inbox.',
    detailedDescription: 'Access your Google Mail inbox directly.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'Mail',
    webUrl: 'https://mail.google.com',
    seoTitle: 'Open Gmail — NINJA Web Launcher',
    seoDescription: 'Instant launcher for Google Mail.',
    keywords: ['open gmail', 'google mail'],
  },
  {
    id: 'open-maps',
    slug: 'open-maps',
    name: 'Open Google Maps',
    shortDescription: 'Launch Google Maps navigation and location search.',
    detailedDescription: 'Open Google Maps in a new tab for directions, traffic, and locations.',
    category: 'web',
    acceptedInputs: ['none'],
    icon: 'MapPin',
    webUrl: 'https://maps.google.com',
    seoTitle: 'Open Google Maps — NINJA Web Launcher',
    seoDescription: 'Instant launcher for Google Maps.',
    keywords: ['open google maps', 'maps'],
  },
];

export const CATEGORIES: { id: string; name: string; description: string; icon: string }[] = [
  { id: 'all', name: 'All Tools', description: 'Explore the complete NINJA utility ecosystem', icon: 'Grid' },
  { id: 'file', name: 'File Tools', description: 'Compress, convert, merge, and manipulate files', icon: 'FileArchive' },
  { id: 'calculators', name: 'Calculators', description: 'Loan EMI, currency, GST, percentages, and math', icon: 'Calculator' },
  { id: 'generators', name: 'Generators', description: 'QR codes, strong passwords, UUIDs, and palettes', icon: 'Sparkles' },
  { id: 'text', name: 'Text & Strings', description: 'Word counts, JSON formatter, case converter, cleaning', icon: 'Type' },
  { id: 'developer', name: 'Developer', description: 'JWT decoder, Base64, URL encoding, regex testing', icon: 'Terminal' },
  { id: 'ai', name: 'AI Workflows', description: 'Summarizer, translator, resume builder, rewriter', icon: 'Bot' },
  { id: 'web', name: 'Web Launcher', description: 'Direct official shortcuts to your favorite web apps', icon: 'ExternalLink' },
];

export const SAMPLE_COMMANDS = [
  'Compress my PDF',
  'Create a QR code for my Instagram',
  'Calculate EMI for 500000 at 9 percent for 5 years',
  'Summarize this document',
  'Resize this image to 1080x1080',
  'Convert image to JPG',
  'Generate a strong password',
  'Open WhatsApp',
  'Convert 10 USD to INR',
  'Translate this text to Kannada',
  'Generate a resume',
  'Format JSON',
];
